name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  backend:
    name: Build Monolith Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build backend jar
        env:
          NEON_DB_URL: ${{ secrets.NEON_DB_URL }}
          NEON_DB_USER: ${{ secrets.NEON_DB_USER }}
          NEON_DB_PASS: ${{ secrets.NEON_DB_PASS }}
          UPSTASH_REDIS_URL: ${{ secrets.UPSTASH_REDIS_URL }}
          UPSTASH_REDIS_TOKEN: ${{ secrets.UPSTASH_REDIS_TOKEN }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: mvn -B -DskipTests package

      - name: Build Docker image
        run: docker build -t manabandhu-backend:ci .
